### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/postcss-jit-props#16]
- [ ] should check if `:root` is in the stylesheet already or not
- [ ] should check if that existing `:root` has props already before injecting

```css
:root {
  --red: red;
}

p {
  color: var(--blue);
}
```

should be:

```css
:root {
  --red: red;
  --blue: blue;
}

p {
  color: var(--blue);
}
```

not:

```css
:root {
  --red: red;
}

:root {
  --blue: blue;
}

p {
  color: var(--blue);
}
```
