### ISSUE TITLE
How can I manage dark-mode properties?

### ISSUE THREAD

**Issue by massimo-cassandro** [GoogleChromeLabs/postcss-jit-props#55]
Maybe I missed something, but if I set dark-mode properties, postcss-jit-props uses only them instead of default ones. 

This is my posstcss config (with webpack):

```javascript
require('postcss-jit-props')({
  files: [path.resolve(__dirname, './src/my-custom-properties.css')],
  ...require('open-props'),
  custom_selector: ':where(html)'
}),
```

and this is an excerpt of `my-custom-properties.css`:

```css
:root {
  color-scheme: light dark;

  --text-color: var(--gray-11);
  --body-bg-color: var(--stone-1);
}

@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;

    --text-color: var(--gray-1);
    --body-bg-color: var(--stone-11);
  }
}
```

This way, `--text-color` and `--body-bg-color` are instantiated with their dark color only.

What am I doing wrong?
